# Generated by Django 4.1.2 on 2022-10-25 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('Created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Published_year', models.IntegerField()),
            ],
        ),
    ]
