# Generated by Django 4.1.2 on 2022-10-26 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelf', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_link',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='freeshelf.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
